version: "1"
services:
  - type: web
    name: cyberbullying-detector-docker
    env: docker
    plan: free
    buildCommand: "docker build -t cyberbullying-detector ."
    startCommand: "docker run -p $PORT:5000 cyberbullying-detector"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
